categories:
- Tool Dependency Packages
owner: biopython
homepage_url: http://biopython.org
remote_repository_url: https://github.com/biopython/galaxy_packages/tree/master/package_biopython_1_66
description: Downloads and compiles version 1.66 of the Biopython package.
long_description: |
  The Biopython Project is an international association of developers of freely available
  Python tools for computational molecular biology.
categories:
name: package_python_2_7_biopython_1_66
type: tool_dependency_definition
